config/routes.rb
Congreso::Application.routes.draw do

  namespace :admin do

      root :to => 'members#index'

      controller :sessions do
        get  'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
      end

      resources :users
      resources :states
      resources :members
      resources :commissions
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :members do
        collection do
          
          get 'nearby'
          get 'diputados'
          get 'senadores'

          match '/:id/initiatives', :to => 'members#initiatives'
          match '/:id/votes', :to => 'members#votes'
          match '/:id/attendances', :to => 'members#attendances'

	      end
      end

      resources :commissions

    end
  end

end

app/models/commission.rb
class Commission < ActiveRecord::Base
  attr_accessible :id, :name
  has_and_belongs_to_many :members
end

app/controllers/admin/commissions_controller.rb
module Admin
  class CommissionsController < BaseController
    # GET /commissions
    # GET /commissions.json
    def index
      @commissions = Commission.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @commissions }
      end
    end

    # GET /commissions/1
    # GET /commissions/1.json
    def show
      @commission = Commission.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @commission }
      end
    end

    # GET /commissions/new
    # GET /commissions/new.json
    def new
      @commission = Commission.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @commission }
      end
    end

    # GET /commissions/1/edit
    def edit
      @commission = Commission.find(params[:id])
    end

    # POST /commissions
    # POST /commissions.json
    def create
      @commission = Commission.new(params[:commission])

      respond_to do |format|
        if @commission.save
          format.html { redirect_to @commission, notice: 'Commission was successfully created.' }
          format.json { render json: @commission, status: :created, location: @commission }
        else
          format.html { render action: "new" }
          format.json { render json: @commission.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /commissions/1
    # PUT /commissions/1.json
    def update
      @commission = Commission.find(params[:id])

      respond_to do |format|
        if @commission.update_attributes(params[:commission])
          format.html { redirect_to @commission, notice: 'Commission was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @commission.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /commissions/1
    # DELETE /commissions/1.json
    def destroy
      @commission = Commission.find(params[:id])
      @commission.destroy

      respond_to do |format|
        format.html { redirect_to commissions_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/api/v1/commissions_controller.rb
module Api
    module V1
    	class CommissionsController < ApplicationController
	    	skip_before_filter :authorize

	    	def index
	    		@commissions = Commission.all
				@status = @commissions.blank? ? "NO_RESULTS" : "OK"
				self.response.headers["Content-Type"] = "application/json; charset=UTF-8"
	    	end

	    	def show
	    		@commission = Commission.find(params[:id])
	    		@status = @commission.blank? ? "NO_RESULTS" : "OK"
				self.response.headers["Content-Type"] = "application/json; charset=UTF-8"
	    	end

		end
    end
end

app/helpers/commissions_helper.rb
module CommissionsHelper
end

app/views/admin/commissions/_form.html.erb
<%= form_for [:admin, @commission]  do |f| %>
  <% if @commission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commission.errors.count, "error") %> prohibited this commission from being saved:</h2>

      <ul>
      <% @commission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/commissions/edit.html.erb
<h1>Editar comisión</h1>

<%= render 'form' %>

<%= link_to 'Show',  [:admin, @commission], :class => 'btn' %> |
<%= link_to 'Back', admin_commissions_path, :class => 'btn' %>

app/views/admin/commissions/index.html.erb
<h1>Comisiones</h1>

<table class="table table-bordered">
  <tr>
    <th>Nombre</th>
    <th>Miembros</th>
    <th></th>
    <th></th>
  </tr>

<% @commissions.each do |commission| %>
  <tr>
    <td><%= link_to commission.name, admin_commission_path(commission) %></td>
    <td><%= commission.members.count %></td>
    <td><%= link_to 'Edit', edit_admin_commission_path(commission), :class => "btn btn-small" %></td>
    <td><%= link_to 'Destroy', [:admin, commission], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nueva comisión', new_admin_commission_path, :class => "btn btn-primary" %>

app/views/admin/commissions/new.html.erb
<h1>Nueva comisión</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_commissions_path %>

app/views/admin/commissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @commission.id %>
</p>

<p>
  <b>Name:</b>
  <%= @commission.name %>
</p>


<%= link_to 'Edit', edit_admin_commission_path(@commission), :class => 'btn' %>
<%= link_to 'Back', admin_commissions_path, :class => 'btn' %>