config/routes.rb
Congreso::Application.routes.draw do

  namespace :admin do

      root :to => 'members#index'

      controller :sessions do
        get  'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
      end

      resources :users
      resources :states
      resources :members
      resources :commissions
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :members do
        collection do
          
          get 'nearby'
          get 'diputados'
          get 'senadores'

          match '/:id/initiatives', :to => 'members#initiatives'
          match '/:id/votes', :to => 'members#votes'
          match '/:id/attendances', :to => 'members#attendances'

	      end
      end

      resources :commissions

    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation
  validates :username, presence: true, uniqueness: true
  has_secure_password
  
  after_destroy :ensure_an_admin_remains
  
  private
    def ensure_an_admin_remains
	if User.count.zero?
	    raise "Can't delete last user"
	end
    end

end

app/controllers/admin/users_controller.rb
module Admin
    class UsersController < BaseController
	# GET /users
	# GET /users.json
	def index
	    @users = User.all

	    respond_to do |format|
		format.html # index.html.erb
	    end
	end

	# GET /users/1
	# GET /users/1.json
	def show
	    @user = User.find(params[:id])

	    respond_to do |format|
		format.html # show.html.erb
	    end
	end

	# GET /users/new
	# GET /users/new.json
	def new
	    @user = User.new

	    respond_to do |format|
		format.html # new.html.erb
	    end
	end

	# GET /users/1/edit
	def edit
	    @user = User.find(params[:id])
	end

	# POST /users
	# POST /users.json
	def create
	    @user = User.new(params[:user])

	    respond_to do |format|
		if @user.save
		    format.html { redirect_to admin_users_url, notice: "User #{@user.username} was successfully created." }
		else
		    format.html { render action: "new" }
		end
	    end
	end

	# PUT /users/1
	# PUT /users/1.json
	def update
	    @user = User.find(params[:id])

	    respond_to do |format|
		if @user.update_attributes(params[:user])
		    format.html { redirect_to admin_users_url, notice: "User #{@user.username} was successfully updated." }
		else
		    format.html { render action: "edit" }
		end
	    end
	end

	# DELETE /users/1
	# DELETE /users/1.json
	def destroy
	    @user = User.find(params[:id])
	    begin
		@user.destroy
		flash[:notice] = "User #{@user.username} deleted"
	    rescue Exception => e
		flash[:notice] = e.message
	    end

	    respond_to do |format|
		format.html { redirect_to admin_users_url }
	    end
	end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password, size: 40 %>
</div>

<div class="field">
    <%= f.label :password_confirmation, 'Confirm' %>
    <%= f.password_field :password_confirmation, size: 40 %>
</div>

  <div class="actions">
      <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @user], :class => 'btn' %>
<%= link_to 'Back', admin_users_path, :class => 'btn' %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<% if notice %>
    <div class="alert alert-info"><%= notice %></div>
<% end %>

<table class="table table-bordered">
  <tr>
    <th>Username</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password_digest %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user), :class => 'btn btn-small' %></td>
    <td><%= link_to 'Destroy', [:admin, user], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-small btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_admin_user_path, :class => 'btn btn-primary' %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path, :class => 'btn' %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>


<%= link_to 'Edit', edit_admin_user_path(@user), :class => 'btn' %>
<%= link_to 'Back', [:admin, users_path], :class => 'btn' %>