config/routes.rb
Congreso::Application.routes.draw do

  namespace :admin do

      root :to => 'members#index'

      controller :sessions do
        get  'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
      end

      resources :users
      resources :states
      resources :members
      resources :commissions
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :members do
        collection do
          
          get 'nearby'
          get 'diputados'
          get 'senadores'

          match '/:id/initiatives', :to => 'members#initiatives'
          match '/:id/votes', :to => 'members#votes'
          match '/:id/attendances', :to => 'members#attendances'

	      end
      end

      resources :commissions

    end
  end

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :id, :name, :division, :geom
  has_many :members
end

app/controllers/admin/states_controller.rb
module Admin
    class StatesController < BaseController
	# GET /states
	# GET /states.json
	def index
	    @states = State.all

	    respond_to do |format|
		format.html # index.html.erb
	    end
	end

	# GET /states/1
	# GET /states/1.json
	def show
	    @state = State.find(params[:id])

	    respond_to do |format|
		format.html # show.html.erb
	    end
	end

	# GET /states/new
	# GET /states/new.json
	def new
	    @state = State.new

	    respond_to do |format|
		format.html # new.html.erb
	    end
	end

	# GET /states/1/edit
	def edit
	    @state = State.find(params[:id])
	end

	# POST /states
	# POST /states.json
	def create
	    @state = State.new(params[:state])

	    respond_to do |format|
		if @state.save
		    format.html { redirect_to [:admin, @state], notice: 'State was successfully created.' }
		else
		    format.html { render action: "new" }
		end
	    end
	end

	# PUT /states/1
	# PUT /states/1.json
	def update
	    @state = State.find(params[:id])

	    respond_to do |format|
		if @state.update_attributes(params[:state])
		    format.html { redirect_to [:admin, @state], notice: 'State was successfully updated.' }
		else
		    format.html { render action: "edit" }
		end
	    end
	end

	# DELETE /states/1
	# DELETE /states/1.json
	def destroy
	    @state = State.find(params[:id])
	    @state.destroy

	    respond_to do |format|
		format.html { redirect_to admin_states_url }
	    end
	end
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @entidad] do |f| %>
  <% if @entidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entidad.errors.count, "error") %> prohibited this entidad from being saved:</h2>

      <ul>
      <% @entidad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :zoom %>
    <%= f.text_field :zoom %>
  </div>
  <div class="field">
    <%= f.label :space %>
    <%= f.number_field :space %>
  </div>
  <div class="actions">
      <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/states/edit.html.erb
<h1>Editando entidad</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @entidad], :class => 'btn' %>
<%= link_to 'Back', admin_entidades_path, :class => 'btn' %>

app/views/admin/states/index.html.erb
<h1>Listing states</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Zoom</th>
    <th>Space</th>
    <th></th>
    <th></th>
  </tr>

<% @states.each do |state| %>
  <tr>
    <td><%= link_to state.name, admin_state_path(state) %></td>
    <td><%= state.code %></td>
    <td><%= state.latitude %></td>
    <td><%= state.longitude %></td>
    <td><%= state.zoom %></td>
    <td><%= state.space %></td>
    <td><%= link_to 'Edit', edit_admin_state_path(state), :class => "btn btn-small" %></td>
    <td><%= link_to 'Destroy', [:admin, state], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-small btn-danger" %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New State', new_admin_state_path, :class => "btn btn-primary" %>

app/views/admin/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', [:admin, states_path], :class => 'btn' %>

app/views/admin/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @state.name %>
</p>

<p>
  <b>Code:</b>
  <%= @state.code %>
</p>

<p>
  <b>Latitude:</b>
  <%= @state.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @state.longitude %>
</p>

<p>
  <b>Zoom:</b>
  <%= @state.zoom %>
</p>

<p>
  <b>Space:</b>
  <%= @state.space %>
</p>


<%= link_to 'Edit', edit_admin_state_path(@state), :class => 'btn' %>
<%= link_to 'Back', admin_states_path, :class => 'btn' %>