config/routes.rb
Congreso::Application.routes.draw do

  namespace :admin do

      root :to => 'members#index'

      controller :sessions do
        get  'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy
      end

      resources :users
      resources :states
      resources :members
      resources :commissions
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :members do
        collection do
          
          get 'nearby'
          get 'diputados'
          get 'senadores'

          match '/:id/initiatives', :to => 'members#initiatives'
          match '/:id/votes', :to => 'members#votes'
          match '/:id/attendances', :to => 'members#attendances'

	      end
      end

      resources :commissions

    end
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Congreso Admin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="navbar navbar-inverse">
	<div class="navbar-inner">
	    <div class="container">
		<a class="brand" href="#">Congreso Admin</a>
		<div class="nav-collapse">
		    <% if session[:user_id] %>
		    <ul class="nav">
			<li><%= link_to "Legisladores", admin_members_path %></li>
			<li><%= link_to "Comisiones", admin_commissions_path %></li>
			<li><%= link_to "Estados", admin_states_path  %></li>
			<li><%= link_to "Usuarios", admin_users_path %></li>
			<li><%= link_to 'Logout', admin_logout_path, method: :delete %></li>
		    </ul>
		    <% end %>
		</div>
	    </div>
	</div>
    </div>

<div class="container">
    <div class="row">
	<div class="span12">
	    <!-- body content -->

	    <%= yield %>
	</div>
    </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cajeros México</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="navbar navbar-inverse">
	<div class="navbar-inner">
	    <div class="container">
		<a class="brand" href="#">Cajeros México Admin</a>
		<div class="nav-collapse">
		    <% if session[:user_id] %>
		    <ul class="nav">
			<li><%= link_to "Atms", atms_path %></li>
			<li><%= link_to "Banks", banks_path %></li>
			<li><%= link_to "Municipalities", municipalities_path %></li>
			<li><%= link_to "States", states_path  %></li>
			<li><%= link_to "Users", users_path %></li>
			<li><%= link_to "Reports", reports_path %></li>
			<li><%= link_to 'Logout', logout_path, method: :delete %></li>
		    </ul>
		    <% end %>
		</div>
	    </div>
	</div>
    </div>

<div class="container">
    <div class="row">
	<div class="span12">
	    <!-- body content -->

	    <%= yield %>
	</div>
    </div>
</div>
</body>
</html>